name: 'Bazel build action'
description: 'Build smth with Bazel'
inputs:
  target:
    description: 'Bazel targets to be built'
    required: true
    default: '//...'
outputs:
  bazel_bin:
    description: 'Bazel targets to be built'
    value: ${{ steps.bazel_bin_path.outputs.result }}
  bazel_output:
    description: 'Bazel targets to be built'
    value: ${{ steps.package_name.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: mkdir for bzl output
      run: mkdir -p /tmp/build_output/
      shell: bash
    - name: Run bazel in Docker container
      id: bazel_build
      run: docker run -p 8888:8888 -e USER="$(id -u)" -u="$(id -u)"
       -v "$(pwd)":/workspace -v /tmp/build_output:/tmp/build_output
       -w /workspace gcr.io/bazel-public/bazel:latest
       --output_user_root=/tmp/build_output build ${{ inputs.target }}
      shell: bash
    - name: bazel output dir
      id: bazel_bin_path
      run: echo "result=$(realpath bazel-bin)" >> $GITHUB_OUTPUT
      shell: bash
    - name: List output dir
      id: package_name
      run: echo "result=$(ls ${{ steps.bazel-bin.outputs.result }}/bazel/expand_template)" >> $GITHUB_OUTPUT
      shell: bash
