name: 'Bazel build action'
description: 'Build smth with Bazel'
inputs:
  target:
    description: 'Bazel targets to be built'
    required: true
    default: '//...'
runs:
  using: 'composite'
  steps:
    - name: mkdir for bzl output
      run: mkdir -p /tmp/build_output/
      shell: bash
    - name: Run bazel in Docker container
      id: bazel_build
      run: docker run -p 8888:8888 -e USER="$(id -u)" -u="$(id -u)"
       -v "$(pwd)":/workspace -v /tmp/build_output:/tmp/build_output
       -w /workspace gcr.io/bazel-public/bazel:latest
       --output_user_root=/tmp/build_output build ${{ inputs.target }}
      shell: bash
