- name: Check setup failures
  hosts: localhost
  vars:
    nas_data:
      jc:
        host: nv018910017.bmwgroup.net
        tech_user: qqvipn1@muc
        path_to_shared_folder: "//nv018910017.bmwgroup.net/VIPN_Trace_Storage"
        mount_path_folder: "{{ ansible_user_dir }}/VIPN_Trace_Storage"
      ef:
        host: nv018910240.bmwgroup.net
        tech_user: qqipno0@muc
        path_to_shared_folder: "//nv018910240.bmwgroup.net/IPN_SYSAbs_Trace_Storage_2"
        mount_path_folder: "{{ ansible_user_dir }}/IPN_SYSAbs_Trace_Storage_2"
    coredumps_src_paths: /home/zuul/VIPN_Trace_Storage/IP-Next_POSIX_NAS_Linkage/136354/IPN-10-PERF__I460__minimal_2024-12-24_010058/IPN-10-PERF__I460__minimal__00 Setup Ethernet/01_startMiniRBS/coredump.1616444790.AdMake40msAsilB.376971.core.gz,/home/zuul/VIPN_Trace_Storage/IP-Next_POSIX_NAS_Linkage/136354/IPN-10-PERF__I460__minimal_2024-12-24_010058/IPN-10-PERF__I460__minimal__Codierung EES25/0003_CodingTest-CodingTime/coredump.1616444439.nform.381075.core.gz
    backtrace_src_paths: /home/zuul/logs/backtrace_automation/master/extracted_backtrace/136354/backtrace.coredump.1616444790.AdMake40msAsilB.376971.core.gz
    upload_script_pre: /home/dodintsova/work_dir/ddad/platform/aas/tools/backtrace_extraction/backtrace_upload_data.py
  tasks:
    - name: "Append dict: define helper variable"
      set_fact:
        some_value:
          - credentials
          - anything_else

    - name: Coredump list to string
      set_fact:
        coredumps: "{{ some_value | join(',') }}"
      when: some_value is defined and some_value

    - name: Print to console
      debug:
        msg: "{{ coredumps | default(' No values') }}"

    - name: "Append dict: execute append"
      vars:
        pattern: "machine {{ item.value.host }}"
      set_fact:
        nas_data: "{{ nas_data | combine({ item.key: nas_data[item.key] | combine({'smb_creds': 'username=' + item.value.tech_user + ',password=' + pattern }) }) }}"
      loop: "{{ nas_data | dict2items }}"

    - name: Print to console
      debug:
        msg: "{{ nas_data }}"

    - name: Prepare NAS upload paths
      command: "python3 {{ upload_script_pre }} -c='{{ coredumps_src_paths }}' -b='{{ backtrace_src_paths }}'"
      register: backtrace_upload_data

    - name: Print to console
      debug:
        msg: "{{ backtrace_upload_data.stdout }}"

    # - name: Calculate SHA1 for private key
    #   command: cat ~/.ssh/id_rsa_qqipni3
    #   register: key_path
    # - name: Calculate SHA1 for private key
    #   set_fact:
    #     key_sha: "{{ key_path.stdout | hash('sha1') }}"
    # - name: Print to console
    #   debug:
    #     msg: "{{ key_sha }}"

    # - name: Add the private key file to the ssh configuration
    #   lineinfile:
    #     path: ~/.ssh/config
    #     line: IdentityFile ~/.ssh/qqipni3_id_ed25519
    #     insertbefore: BOF
    #     create: true
    #     owner: dodintsova
    #     group: dodintsova
    #     mode: 0600
    # - name: Display netrc contents
    #   command: ssh-agent -s
    #   register: command_output
    #   failed_when: false

    # - name: Print to console
    #   debug:
    #     msg: "{{command_output.stdout}}"
    #   failed_when: false

    # - name: Ensure netrc entries
    #   lineinfile:
    #     path: /tmp/netrc/.netrc
    #     mode: 0600
    #     create: true
    #     insertafter: EOF
    #     regexp: "^machine {{ item.machine }}"
    #     line: >
    #       machine {{ item.machine }}
    #       {% if item.login is defined %}login {{ item.login }}{% endif %}
    #       password {{ item.password }}
    #   with_items: "{{ netrc_entries }}"
    #   register: command_result
    #   ignore_errors: true