- name: Check setup failures
  hosts: localhost
  tasks:
    - name: Display ssh contents
      command: cat {{ ansible_user_dir }}/.ssh/config
      register: config
      failed_when: false

    - name: Print to console
      debug:
        msg: "{{ config.stdout }}"
      failed_when: false

    - name: Display ssh known_hosts contents
      command: cat {{ ansible_user_dir }}/.ssh/known_hosts
      register: known_hosts
      failed_when: false

    - name: Print to console
      debug:
        msg: "{{ known_hosts.stdout }}"
      failed_when: false

    - name: Display .ssh files
      command: ls -al {{ ansible_user_dir }}/.ssh
      register: list_dir
      failed_when: false

    - name: Print to console
      debug:
        msg: "{{ list_dir.stdout }}"
      failed_when: false

    - name: Display ssh file
      command: cat {{ ansible_user_dir }}/.ssh/id_rsa_c0f716a9f01b1f694082cc189f8e316b826a02b9
      register: first_key
      failed_when: false

    - name: Print to console
      debug:
        msg: "{{ first_key.stdout }}"
      failed_when: false

    - name: Connect via first ssh
      command: ssh -i {{ ansible_user_dir }}/.ssh/id_rsa_c0f716a9f01b1f694082cc189f8e316b826a02b9 -v git@cc-github.bmwgroup.net
      register: first_key_res
      failed_when: false

    - name: Print to console
      debug:
        msg: "{{ first_key_res.stdout }}"
      failed_when: false

    - name: Start ssh agent
      shell: |
        eval "$(ssh-agent)"
        ssh-add -l
        ssh-add ~/.ssh/id_rsa_c0f716a9f01b1f694082cc189f8e316b826a02b9
        ssh-add -l
      register: ssh_agent
      failed_when: false

    - name: Print to console
      debug:
        msg: "{{ ssh_agent.stdout }}"
      failed_when: false

    - name: Connect via second ssh
      command: ssh -i {{ ansible_user_dir }}/.ssh/id_rsa_c0f716a9f01b1f694082cc189f8e316b826a02b9 git@cc-github.bmwgroup.net
      register: second_key_res
      failed_when: false

    - name: Print to console
      debug:
        msg: "{{ second_key_res.stdout }}"
      failed_when: false

    - name: Disable retry
      zuul_return:
        data:
          zuul:
            retry: false
