name: Ansible Deployment
on:
  pull_request:
    branches:
      - main
    paths:
      - 'artifacts/**'
  workflow_dispatch:
jobs:
  prepare-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ansible
        run: |
           python3 -m pip install --user pipx
           python3 -m pipx ensurepath
           pipx install ansible
  deploy:
    runs-on: ubuntu-latest
    needs: prepare-workspace
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run deployment PB
        run: ansible-playbook deployment/deploy_01.yaml
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dummy-files
          path: artifacts/*.txt
  verify-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run deployment verification PBs
        run: ansible-playbook deployment/deploy_02.yaml
