name: First Workflow
on: workflow_dispatch
jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Ubuntu version:"
          lsb_release -d
