name: Ansible files & Deployment
on:
  pull_request:
    paths:
      - 'playbooks/**'
jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p playbooks'
