name: Ansible Configurable Matrix
on: workflow_dispatch
jobs:
  prepare-workspace:
    continue-on-error: true
    strategy:
      matrix:
        package: ['ansible', 'merge-pdf']
        option: ['--quiet', '--verbose']
        include:
          - package: 'zuul-client'
            option: '--verbose'
        exclude:
          - package: 'merge-pdf'
            option: '--quiet'
    runs-on: ubuntu-latest
    steps:
      - name: Install package
        run: |
           python3 -m pip install --user pipx
           python3 -m pipx ensurepath
           pipx ${{ matrix.option }} install ${{ matrix.package }}
  output-info:
    uses: ./.github/workflows/manual_output.yaml
    with:
      package: 'package-8.8.8'
    secrets:
      gh_secret: ${{ secrets.test_gh_token }}
  report:
      needs: output-info
      runs-on: ubuntu-latest
      steps:
        - name: Output info
          run: echo "${{ needs.output-info.outputs.result }}"
